package rootcode.roaddamagedetectionserver.pothole.entity;

public enum PotholeRegion {

    GANGWON_GANGNEUNG("강원 강릉시"),
    GANGWON_GOSEONG("강원 고성군"),
    GANGWON_DONGHAE("강원 동해시"),
    GANGWON_SAMCHEOK("강원 삼척시"),
    GANGWON_SOKCHO("강원 속초시"),
    GANGWON_YANGGU("강원 양구군"),
    GANGWON_YANGYANG("강원 양양군"),
    GANGWON_YEONGWOL("강원 영월군"),
    GANGWON_WONJU("강원 원주시"),
    GANGWON_INJE("강원 인제군"),
    GANGWON_JEONGSEON("강원 정선군"),
    GANGWON_CHEORWON("강원 철원군"),
    GANGWON_CHUNCHEON("강원 춘천시"),
    GANGWON_TAEBAEK("강원 태백시"),
    GANGWON_PYEONGCHANG("강원 평창군"),
    GANGWON_HONGCHEON("강원 홍천군"),
    GANGWON_HWACHEON("강원 화천군"),
    GANGWON_HOENGSEONG("강원 횡성군"),
    GYEONGGI_GAPYEONG("경기 가평군"),
    GYEONGGI_GOYANG_DEOKYANG("경기 고양시 덕양구"),
    GYEONGGI_GOYANG_ILSANDONG("경기 고양시 일산동구"),
    GYEONGGI_GOYANG_ILSANSEO("경기 고양시 일산서구"),
    GYEONGGI_GWACHEON("경기 과천시"),
    GYEONGGI_GWANGMYEONG("경기 광명시"),
    GYEONGGI_GWANGJU("경기 광주시"),
    GYEONGGI_GURI("경기 구리시"),
    GYEONGGI_GUNPO("경기 군포시"),
    GYEONGGI_GIMPO("경기 김포시"),
    GYEONGGI_NAMYANGJU("경기 남양주시"),
    GYEONGGI_DONGDUCHEON("경기 동두천시"),
    GYEONGGI_BUCHEON("경기 부천시"),
    GYEONGGI_SEONGNAM_BUNDANG("경기 성남시 분당구"),
    GYEONGGI_SEONGNAM_SUJEONG("경기 성남시 수정구"),
    GYEONGGI_SEONGNAM_JUNGWON("경기 성남시 중원구"),
    GYEONGGI_SUWON_GWONSEON("경기 수원시 권선구"),
    GYEONGGI_SUWON_YEONGTONG("경기 수원시 영통구"),
    GYEONGGI_SUWON_JANGAN("경기 수원시 장안구"),
    GYEONGGI_SUWON_PALDAL("경기 수원시 팔달구"),
    GYEONGGI_SIHEUNG("경기 시흥시"),
    GYEONGGI_ANSAN_DANEON("경기 안산시 단원구"),
    GYEONGGI_ANSAN_SANGROK("경기 안산시 상록구"),
    GYEONGGI_ANSEONG("경기 안성시"),
    GYEONGGI_ANYANG_DONGAN("경기 안양시 동안구"),
    GYEONGGI_ANYANG_MANAN("경기 안양시 만안구"),
    GYEONGGI_YANGJU("경기 양주시"),
    GYEONGGI_YANGPYEONG("경기 양평군"),
    GYEONGGI_YEOJU("경기 여주시"),
    GYEONGGI_YEONCHEON("경기 연천군"),
    GYEONGGI_OSAN("경기 오산시"),
    GYEONGGI_YONGIN_GIHUNG("경기 용인시 기흥구"),
    GYEONGGI_YONGIN_SUJI("경기 용인시 수지구"),
    GYEONGGI_YONGIN_CHEOIN("경기 용인시 처인구"),
    GYEONGGI_UIWANG("경기 의왕시"),
    GYEONGGI_UIJEONGBU("경기 의정부시"),
    GYEONGGI_ICHEON("경기 이천시"),
    GYEONGGI_PAJU("경기 파주시"),
    GYEONGGI_PYEONGTAEK("경기 평택시"),
    GYEONGGI_POCHON("경기 포천시"),
    GYEONGGI_HANAM("경기 하남시"),
    GYEONGGI_HWASEONG("경기 화성시"),
    GYEONGNAM_GEOJE("경상남도 거제시"),
    GYEONGNAM_GEONGCHANG("경상남도 거창군"),
    GYEONGNAM_GOSEONG("경상남도 고성군"),
    GYEONGNAM_GIMHAE("경상남도 김해시"),
    GYEONGNAM_NAMHAE("경상남도 남해군"),
    GYEONGNAM_MILYANG("경상남도 밀양시"),
    GYEONGNAM_SACHEON("경상남도 사천시"),
    GYEONGNAM_SANCHUNG("경상남도 산청군"),
    GYEONGNAM_YANGSAN("경상남도 양산시"),
    GYEONGNAM_UIRYEONG("경상남도 의령군"),
    GYEONGNAM_JINJU("경상남도 진주시"),
    GYEONGNAM_CHANGNYEONG("경상남도 창녕군"),
    GYEONGNAM_CHANGWON_MASANHAPPO("경상남도 창원시 마산합포구"),
    GYEONGNAM_CHANGWON_MASANHOE("경상남도 창원시 마산회원구"),
    GYEONGNAM_CHANGWON_SEONGSAN("경상남도 창원시 성산구"),
    GYEONGNAM_CHANGWON_UICHEONG("경상남도 창원시 의창구"),
    GYEONGNAM_CHANGWON_JINHAE("경상남도 창원시 진해구"),
    GYEONGNAM_TONGYEONG("경상남도 통영시"),
    GYEONGNAM_HADONG("경상남도 하동군"),
    GYEONGNAM_HAMAN("경상남도 함안군"),
    GYEONGNAM_HAMYANG("경상남도 함양군"),
    GYEONGNAM_HAPCHEON("경상남도 합천군"),
    GYEONGBUK_GYEONGSAN("경상북도 경산시"),
    GYEONGBUK_GYEONGJU("경상북도 경주시"),
    GYEONGBUK_GORYEONG("경상북도 고령군"),
    GYEONGBUK_GUMI("경상북도 구미시"),
    GYEONGBUK_GUNWI("경상북도 군위군"),
    GYEONGBUK_GIMCHEON("경상북도 김천시"),
    GYEONGBUK_MUNGYEONG("경상북도 문경시"),
    GYEONGBUK_BONGHWA("경상북도 봉화군"),
    GYEONGBUK_SANGJU("경상북도 상주시"),
    GYEONGBUK_SEONGJU("경상북도 성주군"),
    GYEONGBUK_ANDONG("경상북도 안동시"),
    GYEONGBUK_YEONGDEOK("경상북도 영덕군"),
    GYEONGBUK_YEONGYANG("경상북도 영양군"),
    GYEONGBUK_YEONGJU("경상북도 영주시"),
    GYEONGBUK_YEONGCHEON("경상북도 영천시"),
    GYEONGBUK_YECHON("경상북도 예천군"),
    GYEONGBUK_ULLUNG("경상북도 울릉군"),
    GYEONGBUK_ULLJIN("경상북도 울진군"),
    GYEONGBUK_UISEONG("경상북도 의성군"),
    GYEONGBUK_CHONGDO("경상북도 청도군"),
    GYEONGBUK_CHONGSONG("경상북도 청송군"),
    GYEONGBUK_CHILGOK("경상북도 칠곡군"),
    GYEONGBUK_POHANG_NAM("경상북도 포항시 남구"),
    GYEONGBUK_POHANG_BUK("경상북도 포항시 북구"),
    GWANGJU_GWANGSAN("광주 광산구"),
    GWANGJU_NAM("광주 남구"),
    GWANGJU_DONG("광주 동구"),
    GWANGJU_BUK("광주 북구"),
    GWANGJU_SEO("광주 서구"),
    DAEGU_NAM("대구 남구"),
    DAEGU_DALSEO("대구 달서구"),
    DAEGU_DALSEONG("대구 달성군"),
    DAEGU_DONG("대구 동구"),
    DAEGU_BUK("대구 북구"),
    DAEGU_SEO("대구 서구"),
    DAEGU_SUSEONG("대구 수성구"),
    DAEGU_JUNG("대구 중구"),
    Daejeon_DAEDEOK("대전 대덕구"),
    Daejeon_DONG("대전 동구"),
    Daejeon_SEO("대전 서구"),
    Daejeon_YUSEONG("대전 유성구"),
    Daejeon_JUNG("대전 중구"),
    BUSAN_GANGSEO("부산 강서구"),
    BUSAN_GEUMJEONG("부산 금정구"),
    BUSAN_GIJANG("부산 기장군"),
    BUSAN_NAM("부산 남구"),
    BUSAN_DONG("부산 동구"),
    BUSAN_DONGNAE("부산 동래구"),
    BUSAN_BUSANJIN("부산 부산진구"),
    BUSAN_BUK("부산 북구"),
    BUSAN_SASANG("부산 사상구"),
    BUSAN_SAHO("부산 사하구"),
    BUSAN_SEO("부산 서구"),
    BUSAN_SUYONG("부산 수영구"),
    BUSAN_YEONJE("부산 연제구"),
    BUSAN_YEONGDO("부산 영도구"),
    BUSAN_JUNG("부산 중구"),
    BUSAN_HAEUNDAE("부산 해운대구"),
    SEOUL_GANGNAM("서울 강남구"),
    SEOUL_GANGDONG("서울 강동구"),
    SEOUL_GANGBUK("서울 강북구"),
    SEOUL_GANGSEO("서울 강서구"),
    SEOUL_GWANAK("서울 관악구"),
    SEOUL_GWANGJIN("서울 광진구"),
    SEOUL_GURO("서울 구로구"),
    SEOUL_GEUMCHEON("서울 금천구"),
    SEOUL_NOWON("서울 노원구"),
    SEOUL_DOBONG("서울 도봉구"),
    SEOUL_DONGDAEMUN("서울 동대문구"),
    SEOUL_DONGJAK("서울 동작구"),
    SEOUL_MAPO("서울 마포구"),
    SEOUL_SEODAEMUN("서울 서대문구"),
    SEOUL_SEOCHO("서울 서초구"),
    SEOUL_SEONGDONG("서울 성동구"),
    SEOUL_SEONGBUK("서울 성북구"),
    SEOUL_SONGPA("서울 송파구"),
    SEOUL_YANGCHEON("서울 양천구"),
    SEOUL_YEONGDEUNGPO("서울 영등포구"),
    SEOUL_YONGSAN("서울 용산구"),
    SEOUL_EUNPYEONG("서울 은평구"),
    SEOUL_JONGNO("서울 종로구"),
    SEOUL_JUNG("서울 중구"),
    SEOUL_JUNGNANG("서울 중랑구"),
    SEJONG("세종특별자치시"),
    ULSAN_NAM("울산 남구"),
    ULSAN_DONG("울산 동구"),
    ULSAN_BUK("울산 북구"),
    ULSAN_ULJU("울산 울주군"),
    ULSAN_JUNG("울산 중구"),
    INCHEON_GANGHWA("인천 강화군"),
    INCHEON_GEYANG("인천 계양구"),
    INCHEON_NAM("인천 남구"),
    INCHEON_NAMDONG("인천 남동구"),
    INCHEON_DONG("인천 동구"),
    INCHEON_BUPYEONG("인천 부평구"),
    INCHEON_SEO("인천 서구"),
    INCHEON_YEONSU("인천 연수구"),
    INCHEON_ONGJIN("인천 옹진군"),
    INCHEON_JUNG("인천 중구"),
    JEONNAM_GANGJIN("전라남도 강진군"),
    JEONNAM_GOHEUNG("전라남도 고흥군"),
    JEONNAM_GOKSEONG("전라남도 곡성군"),
    JEONNAM_GWANGYANG("전라남도 광양시"),
    JEONNAM_GURE("전라남도 구례군"),
    JEONNAM_NAJU("전라남도 나주시"),
    JEONNAM_DAMYANG("전라남도 담양군"),
    JEONNAM_MOKPO("전라남도 목포시"),
    JEONNAM_MUAN("전라남도 무안군"),
    JEONNAM_BOSEONG("전라남도 보성군"),
    JEONNAM_SUNCHEON("전라남도 순천시"),
    JEONNAM_SHINAN("전라남도 신안군"),
    JEONNAM_YEOSU("전라남도 여수시"),
    JEONNAM_YEONGGWANG("전라남도 영광군"),
    JEONNAM_YEONGAM("전라남도 영암군"),
    JEONNAM_WANDO("전라남도 완도군"),
    JEONNAM_JANGSEONG("전라남도 장성군"),
    JEONNAM_JANGHEUNG("전라남도 장흥군"),
    JEONNAM_JINDO("전라남도 진도군"),
    JEONNAM_HAMPYEONG("전라남도 함평군"),
    JEONNAM_HAENAM("전라남도 해남군"),
    JEONNAM_HWASUN("전라남도 화순군"),
    JEONBUK_GOCHANG("전라북도 고창군"),
    JEONBUK_GUNSAN("전라북도 군산시"),
    JEONBUK_KIMJE("전라북도 김제시"),
    JEONBUK_NAMWON("전라북도 남원시"),
    JEONBUK_MUJU("전라북도 무주군"),
    JEONBUK_BUAN("전라북도 부안군"),
    JEONBUK_SUNCHANG("전라북도 순창군"),
    JEONBUK_WANJU("전라북도 완주군"),
    JEONBUK_IKSAN("전라북도 익산시"),
    JEONBUK_IMSIL("전라북도 임실군"),
    JEONBUK_JANGSU("전라북도 장수군"),
    JEONBUK_JEONJU_DEOKJIN("전라북도 전주시 덕진구"),
    JEONBUK_JEONJU_WANSAN("전라북도 전주시 완산구"),
    JEONBUK_JEONGEUP("전라북도 정읍시"),
    JEONBUK_JINAN("전라북도 진안군"),
    JEJU_SEOGWIPO("제주특별자치도 서귀포시"),
    JEJU_JEJU("제주특별자치도 제주시"),
    CHUNGNAM_GYEORYONG("충청남도 계룡시"),
    CHUNGNAM_GONGJU("충청남도 공주시"),
    CHUNGNAM_GEUMSAN("충청남도 금산군"),
    CHUNGNAM_NONSAN("충청남도 논산시"),
    CHUNGNAM_DANGJIN("충청남도 당진시"),
    CHUNGNAM_BORYEONG("충청남도 보령시"),
    CHUNGNAM_BUYEO("충청남도 부여군"),
    CHUNGNAM_SEOSAN("충청남도 서산시"),
    CHUNGNAM_SECHEON("충청남도 서천군"),
    CHUNGNAM_ASAN("충청남도 아산시"),
    CHUNGNAM_YESAN("충청남도 예산군"),
    CHUNGNAM_CHEONAN_DONGNAM("충청남도 천안시 동남구"),
    CHUNGNAM_CHEONAN_SEOBUK("충청남도 천안시 서북구"),
    CHUNGNAM_CHEONGYANG("충청남도 청양군"),
    CHUNGNAM_TAEAN("충청남도 태안군"),
    CHUNGNAM_HONGSEONG("충청남도 홍성군"),
    CHUNGBUK_GWANGJU("충청북도 괴산군"),
    CHUNGBUK_DANYANG("충청북도 단양군"),
    CHUNGBUK_BOEUN("충청북도 보은군"),
    CHUNGBUK_YEONGDONG("충청북도 영동군"),
    CHUNGBUK_OKCHEON("충청북도 옥천군"),
    CHUNGBUK_EUMSEONG("충청북도 음성군"),
    CHUNGBUK_JECHEON("충청북도 제천시"),
    CHUNGBUK_JEUNGPEONG("충청북도 증평군"),
    CHUNGBUK_JINCHEON("충청북도 진천군"),
    CHUNGBUK_CHEONGJU_SANGDANG("충청북도 청주시 상당구"),
    CHUNGBUK_CHEONGJU_SEOWON("충청북도 청주시 서원구"),
    CHUNGBUK_CHEONGJU_CHEONGWON("충청북도 청주시 청원구"),
    CHUNGBUK_CHEONGJU_HEUNGDEOK("충청북도 청주시 흥덕구"),
    CHUNGBUK_CHUNGJU("충청북도 충주시"),
    ALL("전국");

    private final String value;

    PotholeRegion(String value) { this.value = value; }

    public static PotholeRegion of(String regionName) {
        for (PotholeRegion potholeRegion : PotholeRegion.values()) {
            if (potholeRegion.value.equals(regionName)) {
                return potholeRegion;
            }
        }
        return PotholeRegion.ALL;
    }
}
